const FETCH_REQUEST = '[post] FETCH_REQUEST';
const FETCH_SUCCESS = '[post] FETCH_SUCCESS';
const FETCH_ERROR = '[post] FETCH_ERROR';
const ADD_COMMENT_SUCCESS = '[post] ADD_COMMENT_SUCCESS';
export default {
  ADD_COMMENT_SUCCESS,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
